trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install -r backend/requirements.txt
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your-Service-Connection-Name>'
    appType: 'webAppLinux'
    appName: 'gaief-demo-app'
    package: '$(System.DefaultWorkingDirectory)/backend'
