trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r backend/requirements.txt
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '0a1881fa-6985-47c8-90ca-e514b0cff23d'
    appType: webAppLinux
    appName: 'gaief-demo-app'
    package: '$(System.DefaultWorkingDirectory)/backend'
